[2025-04-20T15:32:47.586+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_sentiment_model.run_training manual__2025-04-20T15:32:42.240121+00:00 [queued]>
[2025-04-20T15:32:47.598+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_sentiment_model.run_training manual__2025-04-20T15:32:42.240121+00:00 [queued]>
[2025-04-20T15:32:47.599+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-20T15:32:47.626+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_training> on 2025-04-20 15:32:42.240121+00:00
[2025-04-20T15:32:47.631+0000] {standard_task_runner.py:60} INFO - Started process 59 to run task
[2025-04-20T15:32:47.641+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'train_sentiment_model', 'run_training', 'manual__2025-04-20T15:32:42.240121+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpe130ckt9']
[2025-04-20T15:32:47.646+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask run_training
[2025-04-20T15:32:47.759+0000] {task_command.py:423} INFO - Running <TaskInstance: train_sentiment_model.run_training manual__2025-04-20T15:32:42.240121+00:00 [running]> on host 4b4e2cb6377f
[2025-04-20T15:32:47.884+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_sentiment_model' AIRFLOW_CTX_TASK_ID='run_training' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T15:32:42.240121+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T15:32:42.240121+00:00'
[2025-04-20T15:32:47.886+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-20T15:32:47.887+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker-compose run --rm trainer']
[2025-04-20T15:32:47.895+0000] {subprocess.py:86} INFO - Output:
[2025-04-20T15:32:47.905+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: docker-compose: command not found
[2025-04-20T15:32:47.906+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-20T15:32:47.919+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-20T15:32:47.925+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=train_sentiment_model, task_id=run_training, execution_date=20250420T153242, start_date=20250420T153247, end_date=20250420T153247
[2025-04-20T15:32:47.948+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task run_training (Bash command failed. The command returned a non-zero exit code 127.; 59)
[2025-04-20T15:32:47.984+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-20T15:32:48.001+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
