[2025-04-20T15:37:59.210+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_sentiment_model.run_training manual__2025-04-20T15:32:42.240121+00:00 [queued]>
[2025-04-20T15:37:59.241+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_sentiment_model.run_training manual__2025-04-20T15:32:42.240121+00:00 [queued]>
[2025-04-20T15:37:59.242+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-20T15:37:59.342+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_training> on 2025-04-20 15:32:42.240121+00:00
[2025-04-20T15:37:59.365+0000] {standard_task_runner.py:60} INFO - Started process 39 to run task
[2025-04-20T15:37:59.376+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'train_sentiment_model', 'run_training', 'manual__2025-04-20T15:32:42.240121+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpqynxqioj']
[2025-04-20T15:37:59.378+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask run_training
[2025-04-20T15:37:59.695+0000] {task_command.py:423} INFO - Running <TaskInstance: train_sentiment_model.run_training manual__2025-04-20T15:32:42.240121+00:00 [running]> on host 4b4e2cb6377f
[2025-04-20T15:37:59.948+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_sentiment_model' AIRFLOW_CTX_TASK_ID='run_training' AIRFLOW_CTX_EXECUTION_DATE='2025-04-20T15:32:42.240121+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-20T15:32:42.240121+00:00'
[2025-04-20T15:37:59.950+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-20T15:37:59.953+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker-compose run --rm trainer']
[2025-04-20T15:37:59.987+0000] {subprocess.py:86} INFO - Output:
[2025-04-20T15:37:59.995+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: docker-compose: command not found
[2025-04-20T15:37:59.995+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-20T15:38:00.014+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-20T15:38:00.031+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=train_sentiment_model, task_id=run_training, execution_date=20250420T153242, start_date=20250420T153759, end_date=20250420T153800
[2025-04-20T15:38:00.082+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task run_training (Bash command failed. The command returned a non-zero exit code 127.; 39)
[2025-04-20T15:38:00.115+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-20T15:38:00.144+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
